# Generated by Django 5.0.7 on 2024-12-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_task',
            name='delete_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
