# Generated by Django 5.0.7 on 2024-12-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_create_task_delete_time_create_task_isdelete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('Completed', 'Completed'), ('In Progress', 'In Progress')], default='Not Started', max_length=200)),
                ('isDelete', models.BooleanField(default=False)),
                ('delete_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
