# Generated by Django 5.0.7 on 2024-12-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_assign_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_task',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='assign_task',
            name='uname',
            field=models.TextField(default=True),
        ),
    ]
