# Generated by Django 5.0.7 on 2024-12-09 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_assign_task_due_date_assign_task_uname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign_task',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='assign_task',
            name='isDelete',
        ),
        migrations.RemoveField(
            model_name='assign_task',
            name='uname',
        ),
        migrations.AddField(
            model_name='assign_task',
            name='assign_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assign_task',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assign_task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assign_task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='create_task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
