# Generated by Django 5.0.7 on 2024-12-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_assign_task_delete_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_task',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='create_task',
            name='isDelete',
        ),
        migrations.AlterField(
            model_name='assign_task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='create_task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='create_task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
